### ISSUE TITLE
problem with mutiny_prep.py

### ISSUE THREAD

**Issue by miscelll** [Cisco-Talos/mutiny-fuzzer#15]
Please, someone can help me? I don't know what to do, I'm trying to use mutiny fuzzer giving to him a pcap file but he says to me: " unexpected EOF while parsing line0; Processing as c_array..........are you sure you gave a file containing tcpdump pcap o wireshark c_array?"

**Comment by jspadaro** [comment]
You are the second person to report this issue.  I'm wondering if the problem is the recent merge of Python 3 support, which probably broke support for Python 2.

Does going back to commit c12c290bf04397a7e4c6fd8915db4fe040dec20d fix the problem?  That one is prior to any Python 3 changes.

**Comment by jspadaro** [comment]
Hi, it appears there was an issue with bytes vs strings in the Python 3 conversion.  Commit b83d8e34f244a358d7e7b956580c53a6aa3ee7da should fix it.  Please close if so.

**Comment by miscelll** [comment]
Thank you so much James! Now me and my friend Martina are trying to use it
and it works!!!



Il giorno dom 26 giu 2022 alle 19:55 James Spadaro ***@***.***>
ha scritto:

**Comment by jspadaro** [comment]
Glad to hear it

**Comment by jspadaro** [comment]
There was one more issue with encode/decode in Python 3.  I just pushed commit 3f347d292ebf7e4dff596f54757663346222aeb1 that should address that.
